"""update

Revision ID: 28886fc5e41c
Revises: ece326a4e7a8
Create Date: 2025-06-26 13:37:14.367548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28886fc5e41c'
down_revision = 'ece326a4e7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
