"""empty message

Revision ID: 79be94192adc
Revises: 28886fc5e41c
Create Date: 2025-06-27 17:05:36.656642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79be94192adc'
down_revision = '28886fc5e41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.Integer(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('contact')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('contact')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
